import type { Metadata } from "next";
import "./globals.css";
import { Montserrat, Monda, Hind_Madurai } from "next/font/google";

const primary = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

const secondary = Monda({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-monda",
});

const parah = Hind_Madurai({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-hind_madurai",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${primary?.variable} ${secondary?.variable} ${parah?.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
